---
    - name: Loop     # used to repeat multiple task in programing language
      hosts: all
      become: true
      become_method: sudo
      connection: ssh
      ignore_errors: false
      tasks:
      - name: Item
        package: 
          name: "{{item}}"
          state: present
        with_items:
          - httpd 
          - telnet 
          - lftp 
          - unzip 
          - wget 

      - name: command
        command: "{{item}}"
        with_item:
        - "yum install telnet -y"
        - "free -m"
        - "w"